# Generated by Django 2.2 on 2018-07-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_name', models.CharField(max_length=200)),
                ('iss_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phs_name', models.CharField(max_length=200)),
                ('phs_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjt_name', models.CharField(max_length=200)),
                ('pjt_status', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stg_name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsk_name', models.CharField(max_length=200)),
                ('tsk_status', models.IntegerField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Phase')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Task'),
        ),
    ]
