# Generated by Django 2.2 on 2018-07-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stg_order',
            field=models.IntegerField(default=0),
        ),
    ]
